name: Python application

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0  # Ensures all files are pulled, including new ones in PR

      - name: Verify files in PR
        run: ls -R   # Debugging step to check if files exist

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run tests
        id: check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE"
          python .github/test.py

      - name: comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.check.outputs.success == 'false'}}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: 'PR title check'
          recreate: true
          message: |
              ide.PNA0/checker: Be ready for serupu adi 👠
              ${{join(steps.run_tests.outputs.*, '\n')}} 

      - name: comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: 'PR title check'
          recreate: true
          message: |
              ide.PNA0/checker: One 5 star added to your bank account 🌟
              ${{join(steps.run_tests.outputs.*, '\n')}} 
