# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request_target:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Verify files in PR
      run: ls -R 

    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Test with pytest
      run: |
        pip install requests
        python ./.github/test.py
